<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageId>Geta.Integration.Omnium.Sdk</PackageId>
    <Title>NotFound handler Admin UI integration Optimizely</Title>
    <Authors>Geta Digital</Authors>
    <Company>Geta Digital</Company>
    <PackageProjectUrl>https://github.com/Geta/geta-integration-omnium-sdk</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Geta/geta-notfoundhandler.git</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>https://github.com/Geta/geta-integration-omnium-sdk/blob/master/CHANGELOG.md</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.20.0" />
    <PackageReference Include="NSwag.MSBuild" Version="13.20.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="DefineNSWagFileName">
    <PropertyGroup Condition="$(Version.Contains('-alpha'))">
      <NSwagConfigFile>nswag.test.json</NSwagConfigFile>
    </PropertyGroup>
    <PropertyGroup Condition="!$(Version.Contains('-alpha'))">
      <NSwagConfigFile>nswag.json</NSwagConfigFile>
    </PropertyGroup>
  </Target>
  <Target Name="NSwag" BeforeTargets="Build">
    <Exec ConsoleToMSBuild="true" ContinueOnError="true" Command="$(NSwagExe_Net60) run $(NSwagConfigFile) /assembly:$(TargetPath) /variables:Configuration=$(Configuration) /runtime:Net60" WorkingDirectory="$(ProjectDir)">
      <Output TaskParameter="ExitCode" PropertyName="NSwagExitCode" />
      <Output TaskParameter="ConsoleOutput" PropertyName="NSwagOutput" />
    </Exec>
    <Message Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' == '0'" Importance="low" />
    <Error Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' != '0'" />
  </Target>
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\$(Configuration)\$(TargetFramework)\*.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
  </Target>
</Project>
